export const TOGGLE_AUDIO = 'TOGGLE_MICRO'
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO'

export const OPEN_CHAT = 'OPEN_CHAT'
export const CLOSE_CHAT = 'CLOSE_CHAT'
export const ENABLE_MSG_BADGE = 'ENABLE_MSG_BADGE'
export const DISABLE_MSG_BADGE = 'DISABLE_MSG_BADGE'